version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"  # Map the MongoDB port to the host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: password  # MongoDB root password
    volumes:
      - ./database/mongodb/:/data/db  # Persist MongoDB data
